
package ws.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.1 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "SayHiServiceService", targetNamespace = "http://ws/", wsdlLocation = "http://localhost:8080/testjws/service/sayHi?wsdl")
public class SayHiServiceService
    extends Service
{

    private final static URL SAYHISERVICESERVICE_WSDL_LOCATION;

    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/testjws/service/sayHi?wsdl");
        } catch (MalformedURLException e) {
            e.printStackTrace();
        }
        SAYHISERVICESERVICE_WSDL_LOCATION = url;
    }

    public SayHiServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SayHiServiceService() {
        super(SAYHISERVICESERVICE_WSDL_LOCATION, new QName("http://ws/", "SayHiServiceService"));
    }

    /**
     * 
     * @return
     *     returns SayHiService
     */
    @WebEndpoint(name = "SayHiServicePort")
    public SayHiService getSayHiServicePort() {
        return (SayHiService)super.getPort(new QName("http://ws/", "SayHiServicePort"), SayHiService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SayHiService
     */
    @WebEndpoint(name = "SayHiServicePort")
    public SayHiService getSayHiServicePort(WebServiceFeature... features) {
        return (SayHiService)super.getPort(new QName("http://ws/", "SayHiServicePort"), SayHiService.class, features);
    }

}
