
package ws.client2;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.1 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "WebServerService", targetNamespace = "http://agent.manager.ltts.sunline.cn/", wsdlLocation = "http://10.24.0.38:3333/lttsweb?wsdl")
public class WebServerService
    extends Service
{

    private final static URL WEBSERVERSERVICE_WSDL_LOCATION;

    static {
        URL url = null;
        try {
            url = new URL("http://10.24.0.38:3333/lttsweb?wsdl");
        } catch (MalformedURLException e) {
            e.printStackTrace();
        }
        WEBSERVERSERVICE_WSDL_LOCATION = url;
    }

    public WebServerService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WebServerService() {
        super(WEBSERVERSERVICE_WSDL_LOCATION, new QName("http://agent.manager.ltts.sunline.cn/", "WebServerService"));
    }

    /**
     * 
     * @return
     *     returns WebServer
     */
    @WebEndpoint(name = "WebServerPort")
    public WebServer getWebServerPort() {
        return (WebServer)super.getPort(new QName("http://agent.manager.ltts.sunline.cn/", "WebServerPort"), WebServer.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WebServer
     */
    @WebEndpoint(name = "WebServerPort")
    public WebServer getWebServerPort(WebServiceFeature... features) {
        return (WebServer)super.getPort(new QName("http://agent.manager.ltts.sunline.cn/", "WebServerPort"), WebServer.class, features);
    }

}
